# Automatically generated by configure - do not modify
prefix=/usr/local
mandir=/usr/local/share/man
sharedir=/usr/local/share/qemu
MAKE=make
CC=gcc
HAVE_GCC3_OPTIONS=yes
HOST_CC=gcc
AR=ar
STRIP=strip -s -R .comment -R .note
CFLAGS=-O0
LDFLAGS=
ARCH=i386
VERSION=0.5.0
SRC_PATH=/home/meeho/qemu-0.5.0
TARGET_DIRS=i386-softmmu
